// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf3tFyJFq4u35It3DcTlrf0jQO5eCW7CY',
    appId: '1:1000510335944:web:82becf383b5e266cc76efd',
    messagingSenderId: '1000510335944',
    projectId: 'daftar-belanja-dc3cf',
    authDomain: 'daftar-belanja-dc3cf.firebaseapp.com',
    storageBucket: 'daftar-belanja-dc3cf.firebasestorage.app',
    measurementId: 'G-8J1773HK5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy8nEVterP5Q2k2NCLxlhFKlmAhcNftxw',
    appId: '1:1000510335944:android:223b974f3cdc5015c76efd',
    messagingSenderId: '1000510335944',
    projectId: 'daftar-belanja-dc3cf',
    storageBucket: 'daftar-belanja-dc3cf.firebasestorage.app',
  );
}
